export { Hero } from './Hero'
export { Services } from './Services'
export { Portfolio } from './Portfolio'
export { About } from './About'
export { Process } from './Process'
export { Contact } from './Contact'
export { Footer } from './Footer'
